[package]
name = "rqq"
version = "0.1.0"
description = "Retryable Priority Request Queue in Motoko"
repository = "https://github.com/Neutrinomic/rqq"
keywords = [ ]
license = "MIT"

[dependencies]
mosup = "0.1.1"
stableheapbtreemap = "1.5.0"
base = "0.14.0"
vector = "0.4.2"